lang: ja
title: fukata.dev
email: fukata.dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  タイのチェンマイを拠点に活動しているプログラマーです。コロナの影響で戻れずに日本に滞在中。
timezone: Asia/Tokyo
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fukata.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fukata
github_username:  fukata
google_analytics: UA-148224679-1
theme: minima
minima:
  date_format: '%Y-%m-%d'
defaults:
  - scope:
      path: ""
    values:
      toc: true
git_history:
  repo: 'fukata/www.fukata.dev'
mermaid:
  src: '/assets/js/mermaid/mermaid.min.js'
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-git-history
  - jekyll-twitter-plugin
  - jekyll-youtube
  - jekyll-mermaid
include:
  - _headers
exclude:
  - .git
  - .bundle
  - .idea
  - Gemfile
  - Gemfile.lock
  - _config.yml
  - _layouts
  - vendor
  - Rakefile
  - README.md
