name: Deploy

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # see https://github.com/actions/checkout/issues/520#issuecomment-1320838255
          fetch-depth: 2147483647

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: www-fukata-dev
          directory: ./_site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
