on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: ./node_modules/.bin/firebase deploy --only hosting --token $FIREBASE_TOKEN
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: '*Deploy*'
          channel: $${{ secrets.SLACK_CHANNEL }}
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          username: ${{ secrets.SLACK_USERNAME }}